//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iscore.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Addresss
    {
        public int Id { get; set; }
        public int ContactId { get; set; }
        public int AddressType { get; set; }
        public string StreetNumber { get; set; }
        public string StreetAddress { get; set; }
        public string Suburb { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string PostCode { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual LookUp LookUp { get; set; }
    }
}
